export enum PROFILE_LIST_ACTIONS {
  OPEN_DELETE_CONFIRMATION_MODAL = 'OPEN_DELETE_CONFIRMATION_MODAL',
  OPEN_MERGE_PROFILES_MODAL = 'OPEN_MERGE_PROFILES_MODAL',
  OPEN_ADD_TO_PROFILE_LISTS_MODAL = 'OPEN_ADD_TO_PROFILE_LISTS_MODAL',
  OPEN_CREATE_PROFILE_LIST_MODAL = 'OPEN_CREATE_PROFILE_LIST_MODAL',
}

export enum OVERLAY_TYPES {
  DELETE_CONFIRMATION_MODAL = 'DELETE_CONFIRMATION_MODAL',
  MERGE_PROFILES_MODAL = 'MERGE_PROFILES_MODAL',
  ADD_TO_PROFILE_LISTS_MODAL = 'ADD_TO_PROFILE_LISTS_MODAL',
  CREATE_PROFILE_LIST_MODAL = 'CREATE_PROFILE_LIST_MODAL',
}
